### ISSUE TITLE
issue with 7.3.10 upgrade

### ISSUE THREAD

**Issue by vmateti** [Kount/kount-ris-java-sdk#26]
We are trying to upgrade 7.3.9 but unable to do so due to the revision variable issue, we are able to successfully upgrade it to 7.3.10 and facing below error

Could not create plugin of type class org.apache.logging.log4j.core.appender.FileAppender for element File: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.FileManager$FileManagerFactory@6313ce3b] unable to create manager for [../kount-ris-sdk/logs/logfile.log] with data [org.apache.logging.log4j.core.appender.FileManager$FactoryData

**Comment by puporod** [comment]
Hi, we are also experiencing problems using the 7.3.10 version

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.core.LoggerContext
   at project.ear//org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
   at project.ear//org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
   at project.ear//org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
   at project.ear//org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
   at project.ear//org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
   at project.ear//org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
   at project.ear//org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
   at org.apache.logging.log4j.api@2.14.1//org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
   at org.apache.logging.log4j.api@2.14.1//org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
   at project.ear//com.kount.ris.Request.<init>(Request.java:42)
   at project.ear//com.kount.ris.Inquiry.<init>(Inquiry.java:29)
```

**Comment by dharp-kount** [comment]
@puporod That stack trace shows version 2.14.1 of Log4J being called.  Kount's SDK declares a dependency on version 2.16.0 for SDK 7.3.10 or version 2.17.0 for SDK version 7.3.11.  Something else in your pom or build process is pulling in the older, insecure version of log4j.

@vmateti Apologies for the issues with 7.3.9.  That was a build issue and failed release that was corrected with 7.3.10.  The error you listed is typically caused by permissions to the log file or directly.  Please confirm that the user account under which the SDK is running has access to create and write to the log location.
